### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getExtension' of null

### ISSUE THREAD

**Issue by agrande** [agrande/lba2remake#159]
An error occurred on http://lba2remake.xesf.net/ [v0.0.7]

Stacktrace:
```
TypeError: Cannot read property 'getExtension' of null
    at Object.get (http://lba2remake.xesf.net/bundle.js:5:13427)
    at i (http://lba2remake.xesf.net/bundle.js:5:22140)
    at new wt (http://lba2remake.xesf.net/bundle.js:6:5169)
    at a (http://lba2remake.xesf.net/bundle.js:23:29450)
    at o (http://lba2remake.xesf.net/bundle.js:23:28556)
    at t.value (http://lba2remake.xesf.net/bundle.js:24:9287)
    at commitAttachRef (http://lba2remake.xesf.net/bundle.js:88:6004)
    at t (http://lba2remake.xesf.net/bundle.js:88:9148)
    at E (http://lba2remake.xesf.net/bundle.js:88:14638)
    at x (http://lba2remake.xesf.net/bundle.js:88:14333)
```

UserAgent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/64.0.3282.167 Chrome/64.0.3282.167 Safari/537.36`

Details: http://lba2remake.xesf.net/crash/crash_report_1521240935.json

**Comment by agrande** [comment]
I suppose this is caused by target browser not supporting webgl (seems to be on linux).
We need to display a nice message when webgl is not present or badly configured.
