### ISSUE TITLE
Uncaught TypeError: this.state.sceneManager.goto is not a function

### ISSUE THREAD

**Issue by agrande** [agrande/lba2remake#165]
An error occurred on http://lba2remake.xesf.net/ [v0.0.7]]

Stacktrace:
```
TypeError: this.state.sceneManager.goto is not a function
    at t.value (http://lba2remake.xesf.net/bundle.js:24:11521)
    at t.value (http://lba2remake.xesf.net/bundle.js:24:11221)
```

UserAgent: `Mozilla/5.0 (X11; CrOS x86_64 10176.76.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.190 Safari/537.36`

Details: http://lba2remake.xesf.net/crash/crash_report_1521785761.json

**Comment by agrande** [comment]
I'll install a chrome OS VM to test that.

**Comment by agrande** [comment]
Hmm, first tests on Chrome OS VM have audio decoding issues, but otherwise run almost fine (if exception throwing in audio decoding is disabled).
Not sure how to reproduct this one.

**Comment by agrande** [comment]
Keeping it for later...

**Comment by agrande** [comment]
Doesn't seem to be specific to Chrome OS.
I had it too yesterday on the demo site, just after releasing 0.0.9
Seems like it has something to do with using a new release for the first time.
Not sure what exactly could be the root cause.

**Comment by agrande** [comment]
Another (I think related) issue I had when trying the new release for the first time on the demo website.

An error occurred on http://lba2remake.xesf.net/#editor=true [v0.0.9]]

Stacktrace:
```
TypeError: Cannot read property 'index' of null
    at Object.hasChanged (http://lba2remake.xesf.net/bundle.js:73:16422)
    at s.value (http://lba2remake.xesf.net/bundle.js:72:25674)
    at http://lba2remake.xesf.net/bundle.js:74:17454
    at s (http://lba2remake.xesf.net/bundle.js:1:2881)
    at fs (http://lba2remake.xesf.net/bundle.js:2:12318)
    at e (http://lba2remake.xesf.net/bundle.js:74:17424)
```

UserAgent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

Details: http://lba2remake.xesf.net/crash/crash_report_1522320385.json

**Comment by agrande** [comment]
I can't reproduce this. No matter what I try. Seems to only happen the first time in production when updating the bundle. Could be a cache incoherence type of error, or the file still being written while requested by the browser.
Closing this for now, until reproduced.
