### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by agrande** [agrande/lba2remake#174]
An error occurred on http://lba2remake.xesf.net/#editor=true [v0.0.8]]

Stacktrace:
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChildFromContainer (http://lba2remake.xesf.net/bundle.js:90:23454)
    at s (http://lba2remake.xesf.net/bundle.js:89:3317)
    at commitDeletion (http://lba2remake.xesf.net/bundle.js:89:4918)
    at t (http://lba2remake.xesf.net/bundle.js:89:8919)
    at E (http://lba2remake.xesf.net/bundle.js:89:14638)
    at x (http://lba2remake.xesf.net/bundle.js:89:14333)
    at batchedUpdates (http://lba2remake.xesf.net/bundle.js:89:15774)
    at $ (http://lba2remake.xesf.net/bundle.js:88:7490)
    at Le (http://lba2remake.xesf.net/bundle.js:88:11982)
```

UserAgent: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

Details: http://lba2remake.xesf.net/crash/crash_report_1522058900.json

**Comment by agrande** [comment]
Duplicate of #173
