### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by agrande** [agrande/lba2remake#192]
An error occurred on http://lba2remake.xesf.net/#editor=true [v0.0.10]]

Stacktrace:
```
TypeError: Cannot read property 'type' of null
    at a (http://lba2remake.xesf.net/bundle.js:20:31661)
    at name (http://lba2remake.xesf.net/bundle.js:23:2870)
    at s (http://lba2remake.xesf.net/bundle.js:62:26916)
    at t.value (http://lba2remake.xesf.net/bundle.js:63:1010)
    at http://lba2remake.xesf.net/bundle.js:63:908
    at R (http://lba2remake.xesf.net/bundle.js:1:5239)
    at Wu (http://lba2remake.xesf.net/bundle.js:2:26268)
    at t.value (http://lba2remake.xesf.net/bundle.js:63:815)
    at t.value (http://lba2remake.xesf.net/bundle.js:63:540)
    at t.value (http://lba2remake.xesf.net/bundle.js:62:29897)
```

UserAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

Details: https://www.lba2remake.net/crash/crash_report_1523307709.json

**Comment by agrande** [comment]
Comment from Hinatangel:
> I was verifying different scene elements at Twinsen's house, specifically searching for those blue triangles or pointers, but didn't find any. Then, I remembered I saw those in his cellar, and I walked through the door instead of using the locator. I don't think I messed up anything in the scene tool as I tend to leave everything as how it was in the beginning. I don't know if this helps somehow...

**Comment by agrande** [comment]
I think this is the same as #194
