### ISSUE TITLE
Uncaught TypeError: Cannot read property 'updateMatrix' of null

### ISSUE THREAD

**Issue by agrande** [agrande/lba2remake#193]
An error occurred on http://lba2remake.xesf.net/#editor=true [v0.0.10]]

Stacktrace:
```
TypeError: Cannot read property 'updateMatrix' of null
    at s (http://lba2remake.xesf.net/bundle.js:28:6684)
    at o (http://lba2remake.xesf.net/bundle.js:28:6301)
    at i (http://lba2remake.xesf.net/bundle.js:28:6247)
    at i (http://lba2remake.xesf.net/bundle.js:28:5900)
    at i (http://lba2remake.xesf.net/bundle.js:41:28612)
    at t.value (http://lba2remake.xesf.net/bundle.js:29:12592)
    at http://lba2remake.xesf.net/bundle.js:64:18634
    at s (http://lba2remake.xesf.net/bundle.js:1:3432)
    at fs (http://lba2remake.xesf.net/bundle.js:2:12836)
    at e (http://lba2remake.xesf.net/bundle.js:64:18604)
```

UserAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

Details: https://www.lba2remake.net/crash/crash_report_1523363368.json

**Comment by agrande** [comment]
Form Hinatangel:
> I was going to name at Esmer Spacecraft (spying). After a few seconds the cutscene ended and teleported me to Lupin-Bourg. I got this crash when I clicked at the locator the Esmer Spacecraft again, as I didn't have enough time for naming. I tried this again and got the same crash.

**Comment by agrande** [comment]
Seems like this bug was hidding another related one.

**Comment by agrande** [comment]
Nevermind it's not really related.
