### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by agrande** [agrande/lba2remake#194]
An error occurred on http://lba2remake.xesf.net/#editor=true [v0.0.10]]

Stacktrace:
```
TypeError: Cannot read property 'name' of null
    at name (http://lba2remake.xesf.net/bundle.js:22:4687)
    at s (http://lba2remake.xesf.net/bundle.js:62:26916)
    at t.value (http://lba2remake.xesf.net/bundle.js:63:1010)
    at http://lba2remake.xesf.net/bundle.js:63:908
    at R (http://lba2remake.xesf.net/bundle.js:1:5239)
    at Wu (http://lba2remake.xesf.net/bundle.js:2:26268)
    at t.value (http://lba2remake.xesf.net/bundle.js:63:815)
    at t.value (http://lba2remake.xesf.net/bundle.js:63:540)
    at t.value (http://lba2remake.xesf.net/bundle.js:62:29897)
    at l (http://lba2remake.xesf.net/bundle.js:86:28453)
```

UserAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

Details: https://www.lba2remake.net/crash/crash_report_1523447843.json

**Comment by agrande** [comment]
From @Jeffroiscool:
> Clicked on school of magic while having actors expanded while being on scene pearl cavern

**Comment by agrande** [comment]
I couldn't reproduce this.
Is there any more details I should know about @Jeffroiscool ?

**Comment by agrande** [comment]
Could reproduce after all. I didn't understand you meant the actual actor nodes were totally expanded.
