### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by agrande** [agrande/lba2remake#232]
An error occurred on https://www.lba2remake.net/#editor=true [v0.0.13] . "]

Stacktrace:
```
" TypeError: Cannot read property 'value' of undefined
    at Object.render (https://www.lba2remake.net/bundle.js:64:14316)
    at https://www.lba2remake.net/bundle.js:63:27863
    at h (https://www.lba2remake.net/bundle.js:1:3964)
    at ps (https://www.lba2remake.net/bundle.js:2:13085)
    at t.value (https://www.lba2remake.net/bundle.js:63:27780)
    at t.value (https://www.lba2remake.net/bundle.js:63:25097)
    at f (https://www.lba2remake.net/bundle.js:87:31204)
    at beginWork (https://www.lba2remake.net/bundle.js:88:2616)
    at o (https://www.lba2remake.net/bundle.js:88:19070)
    at a (https://www.lba2remake.net/bundle.js:88:19349)
```

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Details: https://www.lba2remake.net/crash/crash_report_39aaddd8-cfbd-4a98-a3c1-27c72e5c9a45.json

**Comment by agrande** [comment]
Editing zones in the graveyard.
