### ISSUE TITLE
npm run dev doesn't work in Windows powershell

### ISSUE THREAD

**Issue by pleasenophp** [agrande/lba2remake#275]
It works in WSL (Ubuntu), but doesn't work in native Windows powershell. My node version is v10.16.0  

Error output:
```

npm run dev

> lba2remake@0.2.0-WIP dev C:\Users\<hidden>\projects\lba2remake
> cross-env NODE_ENV=development node devserver.js

C:\Projects\lba2remake\main.jsx:3
module.exports = ({script, buildNumber}) => (<html lang="en">
                                             ^

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Module._compile (C:\Projects\lba2remake\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .jsx] (C:\Projects\lba2remake\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Projects\lba2remake\devserver.js:16:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lba2remake@0.2.0-WIP dev: `cross-env NODE_ENV=development node devserver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lba2remake@0.2.0-WIP dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by pleasenophp** [comment]
Worked after deleting package-lock.json and node_modules and doing npm install again, then running from a real folder path, not a sym-linked path.
